question_data = [
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "hard",
        "question": "DHCP stands for Dynamic Host Configuration Port.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Olympics tennis court is a giant green screen.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Like his character in &quot;Parks and Recreation&quot;, Aziz Ansari was born in South Carolina.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Linux was first created as an alternative to Windows XP.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The term &quot;GTO&quot; was originated by Ferrari?",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Minecraft wasn&rsquo;t the original name to Minecraft.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"]}
]
